version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        python manage.py migrate
        python manage.py createsuperuser --noinput
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=adminpass
      - DJANGO_SUPERUSER_EMAIL=admin@admin.com
      - SIE_TOKEN=a604e7bef5edb4958e6903e10a0fa6596b9e109eb583fb793458707aec01c9ab
      - SIE_URL=https://www.banxico.org.mx/SieAPIRest/service/v1/series/SF43718/datos/oportuno
    depends_on:
      - db
  test:
    build:
      dockerfile: Dockerfile.test
      context: .
    command: pytest
    volumes:
      - .:/usr/src/app