# Generated by Django 3.2.16 on 2022-10-18 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bond',
            old_name='bought',
            new_name='updated',
        ),
    ]
